In [19]:
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
import sys

import keras.keras as keras

import pathlib
import types

dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"

print(keras.__file__)

c:\Users\vini5\OneDrive\Documents\TF\keras\keras\__init__.py


In [20]:
#
#print(tf.keras.__file__)
data_dir = keras.utils.get_file(
    'flower_photos.tar', origin=dataset_url, extract=True)
data_dir = pathlib.Path(data_dir).with_suffix('')

roses = list(data_dir.glob('roses/*'))


train_ds = keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(180, 180),
  batch_size=32)

val_ds = keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(180, 180),
  batch_size=32)

class_names = train_ds.class_names
print(class_names)

Found 3670 files belonging to 5 classes.
Using 2936 files for training.
Found 3670 files belonging to 5 classes.
Using 734 files for validation.
['daisy', 'dandelion', 'roses', 'sunflowers', 'tulips']


In [21]:
for x, y in train_ds:
    print(x)
    break

tf.Tensor(
[[[[2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   ...
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]]

  [[2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   ...
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]]

  [[2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   ...
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2.55000000e+02 2.55000000e+02 2.55000000e+02]]

  ...

  [[2.55000000e+02 2.55000000e+02 2.55000000e+02]
   [2

In [36]:
file_paths, labels, class_names = keras.utils.dataset_utils.index_directory("./casos","inferred",(".csv"),None,True,123,False)

batch_size = 32
shuffle = True
label_mode = "int"

def lerMedicoes(caminho,stride:int=0, head : bool = True):
    return tf.strings.to_number(tf.strings.split(tf.strings.split(tf.io.read_file(caminho)),sep=","), out_type=tf.float32)[1::stride]

args = {"stride":10,"head":True}

path_ds = tf.data.Dataset.from_tensor_slices(file_paths)
readings_ds = path_ds.map(lambda x:lerMedicoes(x,**args).to_tensor(), num_parallel_calls=tf.data.AUTOTUNE)


if batch_size is not None:
    if shuffle:
        # Shuffle locally at each iteration
        dataset = readings_ds.shuffle(buffer_size=batch_size * 8, seed=123)
    dataset = dataset.batch(batch_size)
else:
    if shuffle:
        dataset = readings_ds.shuffle(buffer_size=1024, seed=123)

readings_ds = readings_ds.prefetch(tf.data.AUTOTUNE)

if label_mode:
        label_ds = keras.utils.dataset_utils.labels_to_dataset(
            labels, label_mode, len(class_names) if class_names else 0
        )
        readings_ds = tf.data.Dataset.zip((readings_ds, label_ds))

# O dataset final será  

for i, x in enumerate(readings_ds):
    print(x[1])



Found 5 files belonging to 5 classes.
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [31]:
x.to_tensor().shape

TensorShape([491520, 16])

In [3]:
import keras.keras as keras

readings_ds = keras.utils.csv_dataset_from_directory("./casos")
for i, x in enumerate(readings_ds):
    print(x[0])

Found 5 files belonging to 5 classes.
tf.Tensor(
[[-4.9777536e+00 -8.3272619e+00  1.2148761e+00 ... -3.3245790e-01
  -2.6818356e-01 -3.6348339e-02]
 [-4.9776831e+00 -8.3430595e+00  1.2149171e+00 ... -3.3772111e-01
  -2.5625470e-01  1.8901138e-02]
 [-4.9732904e+00 -8.3434134e+00  1.2148817e+00 ... -3.5599604e-01
  -2.5582355e-01  4.3618008e-03]
 ...
 [-4.9052820e+00 -8.2393465e+00  1.2149426e+00 ...  2.5731131e-02
   5.0733548e-02  4.2164072e-02]
 [-4.9157667e+00 -8.2436676e+00  1.2149866e+00 ...  8.6257765e-03
   3.6361437e-02  1.0177535e-02]
 [-4.9134288e+00 -8.2652035e+00  1.2149767e+00 ... -2.8655123e-02
   3.3343293e-02  1.0177535e-02]], shape=(491520, 16), dtype=float32)
tf.Tensor(
[[-4.9777536e+00 -8.3272619e+00  1.2148761e+00 ... -3.3245790e-01
  -2.6818356e-01 -3.6348339e-02]
 [-4.9776831e+00 -8.3430595e+00  1.2149171e+00 ... -3.3772111e-01
  -2.5625470e-01  1.8901138e-02]
 [-4.9732904e+00 -8.3434134e+00  1.2148817e+00 ... -3.5599604e-01
  -2.5582355e-01  4.3618008e-03]
 ...
 [